### ISSUE TITLE
dp.kinect error with USB3 @ windows8.1

### ISSUE THREAD

**Issue by sdog** [diablodale/dp.kinect#21]
Needed Information
Your setup
1. Operating system: 
Windows8.1
Intel Core i5-4210U 1.7
Nvida geforce 840M
8 GB DDR3
250GB Harddisc
Only 3x USB3 

2. What version of Kinect v1 drivers (or SDK) you have installed.
Kinect v1 SDK 1.7

3. What version of Max you have installed and if it is registered.
MaxMsp 6.1

Steps to reproduce your issue
1. Detail every step needed to create your issue.
Download dp.kinect and registered. WORKED
Wanted try Speech 
Push Start

Result:
Get error:
dp.kinect: Kinect error 0x8004503A. by starting patch

May USB3 not work with Kinect?

**Comment by diablodale** [comment]
closing this as no repro.
