### ISSUE TITLE
Is there a Demo or screen grabs of how this works?

### ISSUE THREAD

**Issue by Moykul** [diablodale/dp.kinect#28]
Hi Diablodale,

Got this running, kind of, am a Max noob but am familiar with pd. I'm looking at the face tracker specifically a pointer in the right direction would be very appreciated.

regards,

Michael

**Comment by diablodale** [comment]
Yes. included with the download is a demo patch. That and the subpatcher have basic and advanced (subpatch) usage. The later has some face tracking in it.

Please remember to follow the extra setup needed for face tracking at https://github.com/diablodale/dp.kinect/wiki
And that same location describes all the attributes and messages that you will use for your face work.
