### ISSUE TITLE
Use french language with 'speech' dpkinect

### ISSUE THREAD

**Issue by loopiotte** [diablodale/dp.kinect#31]
Hi, 

First, excuse for my bad English..

I'm a french user of dpkinect1 and i want to use french language with 'speech' .

I use MacBook pro retina with bootcamp and Windows 10.
Runtime1,8, 

i download the 'Kinect french language pack' but i don't understand how configure dpkinect for use this pack .

thanks for your response.

**Comment by diablodale** [comment]
Please follow the dp.kinect2 setup guide
https://github.com/diablodale/dp.kinect2/wiki#setup-guide
and in particular step 8 for the speech support

Then on that same page read the wiki for the attributes and messages which support speech.
For example: https://github.com/diablodale/dp.kinect2/wiki/Attributes#audio-and-speech
https://github.com/diablodale/dp.kinect2/wiki/Message-based-Data#speech-recognition

If you have difficulty after reading the documentation above and referring to the working demo patch included in your ZIP download, then please provide all the information I request by referring to https://github.com/diablodale/dp.kinect/issues/18

**Comment by diablodale** [comment]
Please refer to the dp.kinect setup guide
https://github.com/diablodale/dp.kinect/wiki#setup-guide
and in particular step 8 for the speech support

Then on that same page read the wiki for the attributes and messages which support speech such as:
https://github.com/diablodale/dp.kinect/wiki/Attributes#audio-and-speech
https://github.com/diablodale/dp.kinect/wiki/Message-based-Data#speech-recognition

If you have difficulty after reading the documentation above and referring to the working demo patch included in your ZIP download, then please provide all the information I request by referring to https://github.com/diablodale/dp.kinect/issues/18

**Comment by diablodale** [comment]
Have you made progress or resolved your question?

**Comment by loopiotte** [comment]
Hi,

I read the wiki but I dont understand how the dpkinect object use de the
differents librairy of language and if it's an obligation to write a
'grammarfiles'.

excuse me for my bad english..

thanks for your response


2016-02-24 10:25 GMT+01:00 Dale Phurrough <notifications@github.com>:

**Comment by diablodale** [comment]
I can also answer in the German language if that is better for you. Ist Deutsch besser für Ihnen?

Yes. You must write a grxml grammar file. That file changes what the speech recognition hears -> messages you want your patch to receive. I recommend you use the links in my documentation to read about the grxml file. You can also google for grxml and probably find documentation in your native french language. (Or use google translate)

**Comment by loopiotte** [comment]
Thanks you.

envoyé de mon sebsung.
Le 26 févr. 2016 11:56, "Dale Phurrough" <notifications@github.com> a
écrit :
