### ISSUE TITLE
Record depth + video to replay in dp.kinect2

### ISSUE THREAD

**Issue by aartcore** [diablodale/dp.kinect#42]
Hey,

Is it possible to record the depth and video data to load and replay in the object?
In the jit.openni object you can load your recorded .oni files which is very handy when your are testing and programming. Is there also something similar for the dp.kinect2 object?

**Comment by diablodale** [comment]
Hello. Microsoft provides tools for recording and playback of the raw data for the Kinect v1 and Kinect v2 sensors. The tools are both called "Kinect Studio". These are developer oriented tools which you can download from Microsoft in the Kinect for Windows Developer Toolkits.

Microsoft sometimes changes their download links. Here are the links that work today.
* Kinect for Windows v1 Developer Toolkit https://www.microsoft.com/en-us/download/details.aspx?id=40276
* Kinect for Windows v2 SDK https://www.microsoft.com/en-us/download/details.aspx?id=44561

**Comment by aartcore** [comment]
Ah thanks for the links! Is it then also possible to play the recorded files with the dp.kinect2 object in max?

**Comment by diablodale** [comment]
Yes. Both of those tools allow for playback and record. They work independently for all applications by operating directly on the drivers...simulating a sensor at the very low level. Therefore, you will be able to use them with Max.

**Comment by aartcore** [comment]
The Kinect Studio option works to replay the skeleton data, but i didn't manage to get playback the video in the dp.kinect2 object. I test with recording all the different streams but with no luck see the video (rgb or infrared) in the dp.kinect2 object. Is there set with streams which match with the dp.kinect2 object to see if i playback my recording?

Thanks in advance

**Comment by diablodale** [comment]
Kinect Studio is a complex developer tool and outside my realm to provide support. If Kinect Studio is setup correctly and your desired streams are recorded and also played back, then all Kinectv2 software (including dp.kinect2) will work. I have tested this repeatedly.

Microsoft can provide you support for Kinect Studio. I recommend you contact them to get the answers on how to use it. https://developer.microsoft.com/windows/kinect

Or try the Kinect v2 forums at https://social.msdn.microsoft.com/Forums/en-US/home?forum=kinectv2sdk

**Comment by aartcore** [comment]
Ok thanks,

I will check it with microsoft.


Op 5 apr. 2017 16:45 schreef "Dale Phurrough" <notifications@github.com>:

Kinect Studio is a complex developer tool and outside my realm to provide
support. If Kinect Studio is setup correctly and your desired streams are
recorded and also played back, then all Kinectv2 software (including
dp.kinect2) will work. I have tested this repeatedly.

Microsoft can provide you support for Kinect Studio. I recommend you
contact them to get the answers on how to use it.
https://developer.microsoft.com/windows/kinect

Or try the Kinect v2 forums at https://social.msdn.microsoft.
com/Forums/en-US/home?forum=kinectv2sdk

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/diablodale/dp.kinect/issues/42#issuecomment-291884329>,
or mute the thread
