### ISSUE TITLE
Kinect20.Face.x64.dll 2.0.1410.19000. or greater

### ISSUE THREAD

**Issue by saxelectro** [diablodale/dp.kinect#47]
Hello there. Max console shows me this message
dp.Kinect2 requires Kinect20.Face.x64.dll 2.0.1410.19000. or greater +the matching NuiDatabase folder from that release

**Comment by diablodale** [comment]
Hello. I don't have enough information to help you. Please read https://github.com/diablodale/dp.kinect/issues/18 and update this issue with the needed information.

Also, you are reporting a bug for dp.kinect...
However that error message is for dp.kinect2
It is likely you have installed/using the wrong versions.
Setup and install information for them is at https://hidale.com/support/

**Comment by diablodale** [comment]
Hello. I am closing this issue as resolved for now. If you are still having problems, please do provide the diagnostic information so I can further help.

**Comment by saxelectro** [comment]
For the moment I'm using my old kinect 1 with the dp kinect ver1 because working perfectly.
My ASUS ROG PC laptop can't keeping connected with kinect 2 and I haven't time to fix that. When I find time I'll check it further and maybe msg you again. Thanks for the help!


Andreas Mourtzoukos 
Saxophonist / Producer / Cross-Media artist / Digital Scenographer / Webcaster
www.saxelectro.com


 
 
  Στις Πέμ, 24 Ιαν, 2019 στις 17:03, ο χρήστηςDale Phurrough<notifications@github.com> έγραψε:   
Hello. I am closing this issue as resolved for now. If you are still having problems, please do provide the diagnostic information so I can further help.
