### ISSUE TITLE
No Kinect chosen for output.

### ISSUE THREAD

**Issue by RaitoWolf** [diablodale/dp.kinect#49]
## Description

No Kinect chosen for output.

## Setup

* Dell Inspiron 15 7559, 16 GB RAM, 4 GB GTX 960m, Intel i7 6700HQ (I only have USB 3.0 ports)
* Windows 10
* KinectSDK 1.8
* Max 7.3.5 registered
* 1.0.6 trial
* Xbox v1 1414 Kinect

![image](https://user-images.githubusercontent.com/49078961/55261428-9bcb0100-5273-11e9-8770-8c9afdd85603.png)

## Steps to reproduce

1. Start Max 7.
2. Open the dp.kinect help patch
3. Click on "Click to start"
4. Error shows up.
5. Cannot change hardware to 1: xbox v1

What result did you *actually* get? Please provide screenshots when helpful.

## Expected Result

I expected it to work, nothing special to write here.

## Workarounds

Nope. I checked the other threads but they didn't help.

## Max console output

![image](https://user-images.githubusercontent.com/49078961/55260991-75589600-5272-11e9-9e67-6f4d9b44f14c.png)
![image](https://user-images.githubusercontent.com/49078961/55262091-6aebcb80-5275-11e9-9d0d-ce574cf1e36f.png)

**Comment by diablodale** [comment]
This is a duplicate of many previous issues. Please read these https://github.com/diablodale/dp.kinect/issues?utf8=%E2%9C%93&q=is%3Aissue+chosen+for+output

**Comment by diablodale** [comment]
Closing this as a duplicate, known issue, caused by Microsoft's licensing restrictions.
